database:
  url: "mysql+pymysql://root:123456@127.0.0.1:3306/brich"

email:
  enabled: false  # 是否启用邮件通知
  sender: "1985238626@qq.com"
  password: "csykporsppagbffa"
  smtp_server: "smtp.qq.com"
  smtp_port: 587
  receiver: "1985238626@qq.com"

urls:
  1: "https://www.ub8.com/ajax/draw/TWBSSC/result?numOfDraw=3000"
  2: "https://www.ub8.com/ajax/draw/ASHAREF2SSC/result?numOfDraw=3000"
  3: "https://www.ub8.com/ajax/draw/APF10SSC/result?numOfDraw=3000"
  4: "https://www.ub8.com/ajax/draw/BAF5SSC/result?numOfDraw=3000"
  5: "https://www.ub8.com/ajax/draw/BAF3SSC/result?numOfDraw=3000"

thresholds:
  1:
    1: { big: 5, small: 8 }
    2: { big: 5, small: 8 }
    3: { big: 7, small: 8 }
    4: { big: 7, small: 8 }
    5: { big: 7, small: 8 }
  2:
    1: { big: 6, small: 3 }
    2: { big: 6, small: 3 }
    3: { big: 6, small: 6 }
    4: { big: 6, small: 6 }
    5: { big: 6, small: 6 }
  3:
    1: { big: 8, small: 8 }
    2: { big: 8, small: 8 }
    3: { big: 8, small: 8 }
    4: { big: 8, small: 8 }
    5: { big: 8, small: 8 }
  4:
    1: { big: 8, small: 8 }
    2: { big: 8, small: 8 }
    3: { big: 8, small: 8 }
    4: { big: 8, small: 8 }
    5: { big: 8, small: 8 }
  5:
    1: { big: 8, small: 8 }
    2: { big: 8, small: 8 }
    3: { big: 8, small: 8 }
    4: { big: 8, small: 8 }
    5: { big: 8, small: 8 }
